CREATE DATABASE "master";

REVOKE ALL ON DATABASE "master" FROM PUBLIC;
REVOKE CONNECT ON DATABASE "postgres", "template0" FROM PUBLIC;

CREATE ROLE "worker" WITH LOGIN CREATEROLE PASSWORD 'secret';
GRANT CONNECT, CREATE ON DATABASE "master" TO "worker";

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;

\c "master"

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
