CREATE DATABASE "noda" LOCALE 'en_US.UTF-8';

REVOKE ALL ON DATABASE "noda" FROM PUBLIC;
REVOKE CONNECT ON DATABASE "postgres", "template0" FROM PUBLIC;

CREATE ROLE "admin" WITH LOGIN CREATEDB CREATEROLE PASSWORD 'secret';
GRANT CONNECT ON DATABASE "noda" TO "admin";
