REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;

-- schema addons to store extensions

CREATE SCHEMA "addons";
COMMENT ON SCHEMA "addons" IS 'database extensions';

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "addons" TO PUBLIC;
GRANT USAGE ON SCHEMA "addons" TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA "addons"
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA "addons"
  GRANT USAGE ON TYPES TO PUBLIC;

-- install extensions

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA "addons" CASCADE;
