CREATE SCHEMA "common";
ALTER SCHEMA "common" OWNER TO "admin";
COMMENT ON SCHEMA "common" IS 'schema to store utility routines and data types';

GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "common" TO PUBLIC;
GRANT USAGE ON SCHEMA "common" TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA "common"
  GRANT EXECUTE ON ROUTINES TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA "common"
  GRANT USAGE ON TYPES TO PUBLIC;
